version: '3'

services:
  cry_store-backend:
    build: .
    ports:
      - 8005:3031
    environment:
     - MONGO_ENABLED=1
     - MONGO_HOST=cry_store-db
     - MONGO_PORT=27017
     - MONGO_USER=ipv6islove
     - MONGO_PASSWORD=dockerislove

  cry_store-db:
    image: mongo
    volumes:
      - ./cry_store_db_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ipv6islove
      MONGO_INITDB_ROOT_PASSWORD: dockerislove